In [1]:
import numpy as np
import pandas as pd #importando as bibliotecas trabalhadas

Numpy - Arrays e operações avançadas

In [4]:
arr = np.arange(1, 11)   # array de 1 a 10


In [5]:
arr # array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr**2 #elevado ao quadrado

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
np.sqrt(arr) #raiz

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [ ]:
np.eye(3) #matriz identidade

Operações com matrizes

In [8]:
matriz = np.random.randint(1, 10, (3,3)) #matriz randomica de inteiros

In [17]:
matriz #matriz gerada

array([[3, 7, 5],
       [7, 8, 4],
       [9, 2, 2]])

In [16]:
matriz**2 #matriz ao quadrado

array([[ 9, 49, 25],
       [49, 64, 16],
       [81,  4,  4]])

In [15]:
matriz+2 #matriz somada a 2

array([[ 5,  9,  7],
       [ 9, 10,  6],
       [11,  4,  4]])

In [18]:
matriz/3 #matriz e a divisão

array([[1.        , 2.33333333, 1.66666667],
       [2.33333333, 2.66666667, 1.33333333],
       [3.        , 0.66666667, 0.66666667]])

Pandas - Series

In [19]:
serie = pd.Series([10, 20, 30, np.nan, 50], index=['a','b','c','d','e'])

In [20]:
serie #serie gerada

,0
a,10.0
b,20.0
c,30.0
d,NaN
e,50.0


In [24]:
serie.describe() #serie descrita

,0
count,4.000000
mean,27.500000
std,17.078251
min,10.000000
25%,17.500000
50%,25.000000
75%,35.000000
max,50.000000


In [25]:
serie.mean() #media da serie

np.float64(27.5)

In [28]:
serie.max() #maior valor

50.0

In [30]:
serie.min() #menor valor

10.0

DataFrame - Criação e Fatiamento

In [31]:
dados = {
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Daniel'],
    'Idade': [23, 35, 45, 29],
    'Cidade': ['SP', 'RJ', 'BH', 'POA'],
    'Nota': [8.5, 7.0, 9.2, 6.8]
} #dicionário base

In [34]:
df = pd.DataFrame(dados) #associa df a um dataframe do conjunto de dados

In [35]:
df

,Nome,Idade,Cidade,Nota
0,Ana,23,SP,8.5
1,Bruno,35,RJ,7.0
2,Carlos,45,BH,9.2
3,Daniel,29,POA,6.8


In [37]:
df[['Nome','Nota']] #filtro por nome e nota

,Nome,Nota
0,Ana,8.5
1,Bruno,7.0
2,Carlos,9.2
3,Daniel,6.8


In [38]:
df.head(2) #apenas as 2 primeiras linhas

,Nome,Idade,Cidade,Nota
0,Ana,23,SP,8.5
1,Bruno,35,RJ,7.0


Seleção condicional e set_index

In [39]:
df[df['Idade'] > 30] #nomes com 31 anos pra cima

,Nome,Idade,Cidade,Nota
1,Bruno,35,RJ,7.0
2,Carlos,45,BH,9.2


In [40]:
df_indexado = df.set_index('Nome')

In [41]:
df_indexado

,Idade,Cidade,Nota
Nome,,,
Ana,23,SP,8.5
Bruno,35,RJ,7.0
Carlos,45,BH,9.2
Daniel,29,POA,6.8


Índices Multiníveis

In [42]:
multi = pd.DataFrame(
    np.random.randn(4,2),
    index=[['Grupo1','Grupo1','Grupo2','Grupo2'], ['A','B','A','B']],
    columns=['Col1','Col2']
) #dicionário para df

In [43]:
multi

Col1      Col2
Grupo1 A  1.143460  1.209512
       B -0.468296 -1.074114
Grupo2 A -0.085619  0.956555
       B  0.148010 -0.795378

In [45]:
multi.loc['Grupo1'] #filtro

,Col1,Col2
A,1.143460,1.209512
B,-0.468296,-1.074114


Dados Ausentes

In [46]:
serie.isnull()

,0
a,False
b,False
c,False
d,True
e,False


In [48]:
serie_preenchida = serie.fillna(0) #preencher com 0

In [49]:
serie_preenchida

,0
a,10.0
b,20.0
c,30.0
d,0.0
e,50.0


In [52]:
serie.dropna() #seleciona os valores 'False', no fim são os verdadeiro.

,0
a,10.0
b,20.0
c,30.0
e,50.0


GroupBy

In [57]:
df_group = df.groupby('Cidade')['Nota'].mean() #agrupando cidade e nota

In [58]:
df_group

,Nota
Cidade,
BH,9.2
POA,6.8
RJ,7.0
SP,8.5


Concatenar, Juntar e Mesclar


In [59]:
df2 = pd.DataFrame({'Nome':['Ana','Carlos'], 'Salario':[5000,7000]})

In [60]:
df_merge = pd.merge(df, df2, on='Nome', how='left')

In [61]:
df_merge #junção dos dados

,Nome,Idade,Cidade,Nota,Salario
0,Ana,23,SP,8.5,5000.0
1,Bruno,35,RJ,7.0,NaN
2,Carlos,45,BH,9.2,7000.0
3,Daniel,29,POA,6.8,NaN


In [62]:
df_concat = pd.concat([df, df_merge], axis=0)

In [63]:
df_concat #valores relacionados concatenados

,Nome,Idade,Cidade,Nota,Salario
0,Ana,23,SP,8.5,NaN
1,Bruno,35,RJ,7.0,NaN
2,Carlos,45,BH,9.2,NaN
3,Daniel,29,POA,6.8,NaN
0,Ana,23,SP,8.5,5000.0
1,Bruno,35,RJ,7.0,NaN
2,Carlos,45,BH,9.2,7000.0
3,Daniel,29,POA,6.8,NaN


Operações

In [66]:
df['Nota_Ajustada'] = df['Nota'] * 1.1 #multiplicação com df

In [67]:
df

,Nome,Idade,Cidade,Nota,Nota_Ajustada
0,Ana,23,SP,8.5,9.35
1,Bruno,35,RJ,7.0,7.70
2,Carlos,45,BH,9.2,10.12
3,Daniel,29,POA,6.8,7.48


In [68]:
df['Categoria'] = df['Nota'].apply(lambda x: 'Alta' if x >= 8 else 'Baixa') #funçoes

In [69]:
df

,Nome,Idade,Cidade,Nota,Nota_Ajustada,Categoria
0,Ana,23,SP,8.5,9.35,Alta
1,Bruno,35,RJ,7.0,7.70,Baixa
2,Carlos,45,BH,9.2,10.12,Alta
3,Daniel,29,POA,6.8,7.48,Baixa


Entrada e Saída de dados


In [70]:
df.to_csv('dados.csv', index=False) #gerando o csv a partir do df

In [71]:
df_lido = pd.read_csv('dados.csv') #lendo o csv gerado

In [72]:
df_lido

,Nome,Idade,Cidade,Nota,Nota_Ajustada,Categoria
0,Ana,23,SP,8.5,9.35,Alta
1,Bruno,35,RJ,7.0,7.70,Baixa
2,Carlos,45,BH,9.2,10.12,Alta
3,Daniel,29,POA,6.8,7.48,Baixa


Estatísticas


In [77]:
# Criando um DataFrame de exemplo
dados = {
    'Idade': [23, 35, 45, 29, 32],
    'Nota': [8.5, 7.0, 9.2, 6.8, 8.0],
    'Salario': [4000, 5000, 7000, 4500, 6500]
}

In [78]:
df = pd.DataFrame(dados)

In [79]:
correlacao = df.corr()

In [80]:
correlacao # ensinado na ultima aula, a relação entre assuntos na estatística.

,Idade,Nota,Salario
Idade,1.000000,0.368126,0.828570
Nota,0.368126,1.000000,0.516412
Salario,0.828570,0.516412,1.000000
