In [2]:
import numpy as np

In [3]:
minha_lista = [1, 2, 3]

In [4]:
minha_lista

[1, 2, 3]

In [5]:
np.array(minha_lista)

array([1, 2, 3])

Método mais simples de criar um array em numpy, justamente por só chamar a biblioteca e passar a lista.

In [6]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange (0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Forma de montar um array "automático" com numpy, sem o último elemento (10)

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
arr = np.zeros(3)

In [11]:
arr

array([0., 0., 0.])

Também podem ser associados como uma variavel, e vir dentro dela a função np

In [12]:
arr = np.zeros((5, 5))

In [13]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Pra conseguir passar e criar uma de duas dimensoes, passar tupla como referencia


In [14]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Matriz identidade, função capta o numero de linhas e colunas pelo (4)

In [16]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [17]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

Linspace serve pra criar o array espaçado sendo inicio, fim, divisão do espaço.

In [18]:
np.random.rand(5)

array([0.56095505, 0.72075831, 0.6700326 , 0.54841292, 0.64785012])

In [19]:
np.random.rand(5)*100

array([62.36921032, 92.94238749, 63.16941677, 77.27624543, 95.77535525])

In [20]:
np.random.rand(5, 4, 3)

array([[[0.15983   , 0.11810607, 0.04574142],
        [0.12707473, 0.59352296, 0.76607808],
        [0.1941819 , 0.58955148, 0.83227596],
        [0.31465866, 0.01046565, 0.53347793]],

       [[0.52118771, 0.51622441, 0.65463472],
        [0.33590381, 0.89708213, 0.50262075],
        [0.47826914, 0.64963352, 0.07614502],
        [0.34434274, 0.46152806, 0.26240351]],

       [[0.86561093, 0.52937394, 0.57867025],
        [0.46958758, 0.24072469, 0.21918387],
        [0.56604654, 0.0947211 , 0.64307348],
        [0.59885964, 0.32342793, 0.74574609]],

       [[0.72856338, 0.6144731 , 0.1211673 ],
        [0.30682265, 0.63618601, 0.58082235],
        [0.1962968 , 0.29176019, 0.68566863],
        [0.43881442, 0.18531961, 0.22740941]],

       [[0.60829932, 0.16052293, 0.19810294],
        [0.9859263 , 0.92311658, 0.48069096],
        [0.62995858, 0.37768275, 0.56362055],
        [0.737961  , 0.0876444 , 0.30190104]]])

Matrizes com numeros aleatórios

In [21]:
np.random.randn(5)

array([ 1.05426968,  1.03200112, -1.0118053 ,  1.62346052, -1.31137711])

In [22]:
np.random.randn(4)

array([ 0.27528687,  0.28378529, -0.26116026, -1.31203682])

In [23]:
np.random.randint(0, 100, 10)

array([45, 92, 53, 82,  8, 58,  7, 49,  5, 30])

Esse é para tirar aleatorios inteiros, a fim de nao ficar decimal, essa é a justificativa dele.

In [24]:
np.random.rand(5)*100

array([93.50799399, 68.80910523, 71.42287454, 93.3292732 , 62.75351988])

In [25]:
np.round(np.random.rand(5)*100, 0)

array([ 7., 67., 70., 96., 69.])

Equivalente ao randint

In [26]:
arr = np.random.rand(25)

In [27]:
arr

array([0.24510933, 0.89996518, 0.95618181, 0.32019138, 0.79132929,
       0.23167308, 0.4170975 , 0.08601986, 0.86821229, 0.34645991,
       0.45609836, 0.55067537, 0.04778563, 0.07440342, 0.13980695,
       0.09675392, 0.13996956, 0.1709591 , 0.07409667, 0.56956613,
       0.02561865, 0.11573337, 0.8018382 , 0.7758179 , 0.57189314])

In [28]:
arr.reshape(5, 5)

array([[0.24510933, 0.89996518, 0.95618181, 0.32019138, 0.79132929],
       [0.23167308, 0.4170975 , 0.08601986, 0.86821229, 0.34645991],
       [0.45609836, 0.55067537, 0.04778563, 0.07440342, 0.13980695],
       [0.09675392, 0.13996956, 0.1709591 , 0.07409667, 0.56956613],
       [0.02561865, 0.11573337, 0.8018382 , 0.7758179 , 0.57189314]])

Ela formata para outro tamanho, nesse caso, 5x5

In [29]:
arr

array([0.24510933, 0.89996518, 0.95618181, 0.32019138, 0.79132929,
       0.23167308, 0.4170975 , 0.08601986, 0.86821229, 0.34645991,
       0.45609836, 0.55067537, 0.04778563, 0.07440342, 0.13980695,
       0.09675392, 0.13996956, 0.1709591 , 0.07409667, 0.56956613,
       0.02561865, 0.11573337, 0.8018382 , 0.7758179 , 0.57189314])

In [30]:
arr = arr.reshape(5, 5)

In [31]:
arr

array([[0.24510933, 0.89996518, 0.95618181, 0.32019138, 0.79132929],
       [0.23167308, 0.4170975 , 0.08601986, 0.86821229, 0.34645991],
       [0.45609836, 0.55067537, 0.04778563, 0.07440342, 0.13980695],
       [0.09675392, 0.13996956, 0.1709591 , 0.07409667, 0.56956613],
       [0.02561865, 0.11573337, 0.8018382 , 0.7758179 , 0.57189314]])

In [32]:
arr.shape

(5, 5)

In [33]:
arr.max()

np.float64(0.956181807646557)

In [34]:
arr.min()

np.float64(0.02561864738134334)

Shape serve para verificar o tamanho, chama do mesmo jeito que um metodo em POO.

In [35]:
arr.argmax()

np.int32(2)

In [36]:
arr.argmin()

np.int32(20)

Respectivamente, retornam a posição do valor, maior e menor.

Indexação e Fatiamento de arrays

In [37]:
arr = np.arange(0, 30, 3)

In [38]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [39]:
arr[3]

np.int32(9)

In [40]:
arr[2:5]

array([ 6,  9, 12])

O primeiro serve para puxar na terceita posição, [3], quando coloca o : puxa os indicies do primeiro [2], até o ultimo, [5], o próximo é a mesma coisa, mas sem colocar o inicial, começando do 0, e vice e versa.

In [41]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [42]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [43]:
arr[2:] = 100

In [44]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [45]:
arr = np.arange(50).reshape(5, 10) #torna matriz de 5x10

In [46]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [47]:
arr.shape


(5, 10)

In [48]:
arr2 = arr[:3]

Aqui o professor fez varias alterações, mas a ideia é a mesma, limitar até a linha 3.

In [49]:
arr2


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [50]:
arr2 = arr[:3].copy()

In [51]:
arr [1:4, 5:] 

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [52]:
bol = arr > 50

In [53]:
arr[bol]

array([], dtype=int32)

In [54]:
array = np.linspace(0, 100, 30)

In [55]:
array.shape


(30,)

In [56]:
array = array.reshape(3, 10)

In [57]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [58]:
array [0:2, 2]

array([ 6.89655172, 41.37931034])

Mais uma forma de fatiar o array, pega da linha e linha e coluna. Linhas 0 e 2, da coluna 2 nesse caso.

Operações com arrays

In [59]:
arr = np.arange(0, 16)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [63]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [64]:
arr / arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [65]:
arr / 0

array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf])

In [66]:
1 / arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [67]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [68]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [70]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [71]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [73]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [74]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [75]:
np.mean(arr)

np.float64(7.5)

In [76]:
np.std(arr)

np.float64(4.6097722286464435)

In [77]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [78]:
np.max(arr)

np.int32(15)

In [82]:
np.min(arr)

np.int32(0)

In [80]:
arr.max()

np.int32(15)

In [83]:
arr.min()

np.int32(0)

O array pode sofrer qualquer tipo de modificação matematica, incluindo as mais dificies como as raizes e exponenciação, o resto são somas e subtrações, multiplicações ou divisões, o que pode ser util para algumas areas da computação, como geração de senhas e criptografia por array.